# -*- coding: utf-8 -*-
# Auto-generated by Stone, do not modify.
try:
    from . import stone_validators as bv
    from . import stone_base as bb
except (SystemError, ValueError):
    # Catch errors raised when importing a relative module when not in a package.
    # This makes testing this file directly (outside of a package) easier.
    import stone_validators as bv
    import stone_base as bb

try:
    from . import (
        ns2,
    )
except (SystemError, ValueError):
    import ns2

class A(object):
    """
    Sample struct doc.

    :ivar a: Sample field doc.
    """

    __slots__ = [
        '_a_value',
        '_a_present',
        '_b_value',
        '_b_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 a=None,
                 b=None):
        self._a_value = None
        self._a_present = False
        self._b_value = None
        self._b_present = False
        if a is not None:
            self.a = a
        if b is not None:
            self.b = b

    @property
    def a(self):
        """
        Sample field doc.

        :rtype: str
        """
        if self._a_present:
            return self._a_value
        else:
            raise AttributeError("missing required field 'a'")

    @a.setter
    def a(self, val):
        val = self._a_validator.validate(val)
        self._a_value = val
        self._a_present = True

    @a.deleter
    def a(self):
        self._a_value = None
        self._a_present = False

    @property
    def b(self):
        """
        :rtype: long
        """
        if self._b_present:
            return self._b_value
        else:
            raise AttributeError("missing required field 'b'")

    @b.setter
    def b(self, val):
        val = self._b_validator.validate(val)
        self._b_value = val
        self._b_present = True

    @b.deleter
    def b(self):
        self._b_value = None
        self._b_present = False

    def __repr__(self):
        return 'A(a={!r}, b={!r})'.format(
            self._a_value,
            self._b_value,
        )

A_validator = bv.Struct(A)

class B(A):

    __slots__ = [
        '_c_value',
        '_c_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 a=None,
                 b=None,
                 c=None):
        super(B, self).__init__(a,
                                b)
        self._c_value = None
        self._c_present = False
        if c is not None:
            self.c = c

    @property
    def c(self):
        """
        :rtype: bytes
        """
        if self._c_present:
            return self._c_value
        else:
            raise AttributeError("missing required field 'c'")

    @c.setter
    def c(self, val):
        val = self._c_validator.validate(val)
        self._c_value = val
        self._c_present = True

    @c.deleter
    def c(self):
        self._c_value = None
        self._c_present = False

    def __repr__(self):
        return 'B(a={!r}, b={!r}, c={!r})'.format(
            self._a_value,
            self._b_value,
            self._c_value,
        )

B_validator = bv.Struct(B)

class C(B):

    __slots__ = [
        '_d_value',
        '_d_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 a=None,
                 b=None,
                 c=None,
                 d=None):
        super(C, self).__init__(a,
                                b,
                                c)
        self._d_value = None
        self._d_present = False
        if d is not None:
            self.d = d

    @property
    def d(self):
        """
        :rtype: float
        """
        if self._d_present:
            return self._d_value
        else:
            raise AttributeError("missing required field 'd'")

    @d.setter
    def d(self, val):
        val = self._d_validator.validate(val)
        self._d_value = val
        self._d_present = True

    @d.deleter
    def d(self):
        self._d_value = None
        self._d_present = False

    def __repr__(self):
        return 'C(a={!r}, b={!r}, c={!r}, d={!r})'.format(
            self._a_value,
            self._b_value,
            self._c_value,
            self._d_value,
        )

C_validator = bv.Struct(C)

class ContainsAlias(object):

    __slots__ = [
        '_s_value',
        '_s_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 s=None):
        self._s_value = None
        self._s_present = False
        if s is not None:
            self.s = s

    @property
    def s(self):
        """
        :rtype: str
        """
        if self._s_present:
            return self._s_value
        else:
            raise AttributeError("missing required field 's'")

    @s.setter
    def s(self, val):
        val = self._s_validator.validate(val)
        self._s_value = val
        self._s_present = True

    @s.deleter
    def s(self):
        self._s_value = None
        self._s_present = False

    def __repr__(self):
        return 'ContainsAlias(s={!r})'.format(
            self._s_value,
        )

ContainsAlias_validator = bv.Struct(ContainsAlias)

class D(object):

    __slots__ = [
        '_a_value',
        '_a_present',
        '_b_value',
        '_b_present',
        '_c_value',
        '_c_present',
        '_d_value',
        '_d_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 a=None,
                 d=None,
                 b=None,
                 c=None):
        self._a_value = None
        self._a_present = False
        self._b_value = None
        self._b_present = False
        self._c_value = None
        self._c_present = False
        self._d_value = None
        self._d_present = False
        if a is not None:
            self.a = a
        if b is not None:
            self.b = b
        if c is not None:
            self.c = c
        if d is not None:
            self.d = d

    @property
    def a(self):
        """
        :rtype: str
        """
        if self._a_present:
            return self._a_value
        else:
            raise AttributeError("missing required field 'a'")

    @a.setter
    def a(self, val):
        val = self._a_validator.validate(val)
        self._a_value = val
        self._a_present = True

    @a.deleter
    def a(self):
        self._a_value = None
        self._a_present = False

    @property
    def b(self):
        """
        :rtype: long
        """
        if self._b_present:
            return self._b_value
        else:
            return 10

    @b.setter
    def b(self, val):
        val = self._b_validator.validate(val)
        self._b_value = val
        self._b_present = True

    @b.deleter
    def b(self):
        self._b_value = None
        self._b_present = False

    @property
    def c(self):
        """
        :rtype: str
        """
        if self._c_present:
            return self._c_value
        else:
            return None

    @c.setter
    def c(self, val):
        if val is None:
            del self.c
            return
        val = self._c_validator.validate(val)
        self._c_value = val
        self._c_present = True

    @c.deleter
    def c(self):
        self._c_value = None
        self._c_present = False

    @property
    def d(self):
        """
        :rtype: list of [Optional[long]]
        """
        if self._d_present:
            return self._d_value
        else:
            raise AttributeError("missing required field 'd'")

    @d.setter
    def d(self, val):
        val = self._d_validator.validate(val)
        self._d_value = val
        self._d_present = True

    @d.deleter
    def d(self):
        self._d_value = None
        self._d_present = False

    def __repr__(self):
        return 'D(a={!r}, d={!r}, b={!r}, c={!r})'.format(
            self._a_value,
            self._d_value,
            self._b_value,
            self._c_value,
        )

D_validator = bv.Struct(D)

class DocTest(object):
    """
    :ivar b: If ``True`` then...
    :ivar t: References :class:`D`.
    """

    __slots__ = [
        '_b_value',
        '_b_present',
        '_t_value',
        '_t_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 b=None,
                 t=None):
        self._b_value = None
        self._b_present = False
        self._t_value = None
        self._t_present = False
        if b is not None:
            self.b = b
        if t is not None:
            self.t = t

    @property
    def b(self):
        """
        If ``True`` then...

        :rtype: bool
        """
        if self._b_present:
            return self._b_value
        else:
            raise AttributeError("missing required field 'b'")

    @b.setter
    def b(self, val):
        val = self._b_validator.validate(val)
        self._b_value = val
        self._b_present = True

    @b.deleter
    def b(self):
        self._b_value = None
        self._b_present = False

    @property
    def t(self):
        """
        References :class:`D`.

        :rtype: str
        """
        if self._t_present:
            return self._t_value
        else:
            raise AttributeError("missing required field 't'")

    @t.setter
    def t(self, val):
        val = self._t_validator.validate(val)
        self._t_value = val
        self._t_present = True

    @t.deleter
    def t(self):
        self._t_value = None
        self._t_present = False

    def __repr__(self):
        return 'DocTest(b={!r}, t={!r})'.format(
            self._b_value,
            self._t_value,
        )

DocTest_validator = bv.Struct(DocTest)

class E(object):

    __slots__ = [
        '_a_value',
        '_a_present',
        '_b_value',
        '_b_present',
        '_c_value',
        '_c_present',
    ]

    _has_required_fields = False

    def __init__(self,
                 a=None,
                 b=None,
                 c=None):
        self._a_value = None
        self._a_present = False
        self._b_value = None
        self._b_present = False
        self._c_value = None
        self._c_present = False
        if a is not None:
            self.a = a
        if b is not None:
            self.b = b
        if c is not None:
            self.c = c

    @property
    def a(self):
        """
        :rtype: str
        """
        if self._a_present:
            return self._a_value
        else:
            return 'test'

    @a.setter
    def a(self, val):
        val = self._a_validator.validate(val)
        self._a_value = val
        self._a_present = True

    @a.deleter
    def a(self):
        self._a_value = None
        self._a_present = False

    @property
    def b(self):
        """
        :rtype: long
        """
        if self._b_present:
            return self._b_value
        else:
            return 10

    @b.setter
    def b(self, val):
        val = self._b_validator.validate(val)
        self._b_value = val
        self._b_present = True

    @b.deleter
    def b(self):
        self._b_value = None
        self._b_present = False

    @property
    def c(self):
        """
        :rtype: long
        """
        if self._c_present:
            return self._c_value
        else:
            return None

    @c.setter
    def c(self, val):
        if val is None:
            del self.c
            return
        val = self._c_validator.validate(val)
        self._c_value = val
        self._c_present = True

    @c.deleter
    def c(self):
        self._c_value = None
        self._c_present = False

    def __repr__(self):
        return 'E(a={!r}, b={!r}, c={!r})'.format(
            self._a_value,
            self._b_value,
            self._c_value,
        )

E_validator = bv.Struct(E)

class Resource(object):

    __slots__ = [
        '_name_value',
        '_name_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 name=None):
        self._name_value = None
        self._name_present = False
        if name is not None:
            self.name = name

    @property
    def name(self):
        """
        :rtype: str
        """
        if self._name_present:
            return self._name_value
        else:
            raise AttributeError("missing required field 'name'")

    @name.setter
    def name(self, val):
        val = self._name_validator.validate(val)
        self._name_value = val
        self._name_present = True

    @name.deleter
    def name(self):
        self._name_value = None
        self._name_present = False

    def __repr__(self):
        return 'Resource(name={!r})'.format(
            self._name_value,
        )

Resource_validator = bv.StructTree(Resource)

class File(Resource):

    __slots__ = [
        '_size_value',
        '_size_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 name=None,
                 size=None):
        super(File, self).__init__(name)
        self._size_value = None
        self._size_present = False
        if size is not None:
            self.size = size

    @property
    def size(self):
        """
        :rtype: long
        """
        if self._size_present:
            return self._size_value
        else:
            raise AttributeError("missing required field 'size'")

    @size.setter
    def size(self, val):
        val = self._size_validator.validate(val)
        self._size_value = val
        self._size_present = True

    @size.deleter
    def size(self):
        self._size_value = None
        self._size_present = False

    def __repr__(self):
        return 'File(name={!r}, size={!r})'.format(
            self._name_value,
            self._size_value,
        )

File_validator = bv.Struct(File)

class ResourceLax(object):

    __slots__ = [
        '_name_value',
        '_name_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 name=None):
        self._name_value = None
        self._name_present = False
        if name is not None:
            self.name = name

    @property
    def name(self):
        """
        :rtype: str
        """
        if self._name_present:
            return self._name_value
        else:
            raise AttributeError("missing required field 'name'")

    @name.setter
    def name(self, val):
        val = self._name_validator.validate(val)
        self._name_value = val
        self._name_present = True

    @name.deleter
    def name(self):
        self._name_value = None
        self._name_present = False

    def __repr__(self):
        return 'ResourceLax(name={!r})'.format(
            self._name_value,
        )

ResourceLax_validator = bv.StructTree(ResourceLax)

class File2(ResourceLax):

    __slots__ = [
        '_size_value',
        '_size_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 name=None,
                 size=None):
        super(File2, self).__init__(name)
        self._size_value = None
        self._size_present = False
        if size is not None:
            self.size = size

    @property
    def size(self):
        """
        :rtype: long
        """
        if self._size_present:
            return self._size_value
        else:
            raise AttributeError("missing required field 'size'")

    @size.setter
    def size(self, val):
        val = self._size_validator.validate(val)
        self._size_value = val
        self._size_present = True

    @size.deleter
    def size(self):
        self._size_value = None
        self._size_present = False

    def __repr__(self):
        return 'File2(name={!r}, size={!r})'.format(
            self._name_value,
            self._size_value,
        )

File2_validator = bv.Struct(File2)

class Folder(Resource):
    """
    Regular folder
    """

    __slots__ = [
    ]

    _has_required_fields = True

    def __init__(self,
                 name=None):
        super(Folder, self).__init__(name)

    def __repr__(self):
        return 'Folder(name={!r})'.format(
            self._name_value,
        )

Folder_validator = bv.Struct(Folder)

class Folder2(ResourceLax):
    """
    Regular folder
    """

    __slots__ = [
    ]

    _has_required_fields = True

    def __init__(self,
                 name=None):
        super(Folder2, self).__init__(name)

    def __repr__(self):
        return 'Folder2(name={!r})'.format(
            self._name_value,
        )

Folder2_validator = bv.Struct(Folder2)

class ImportTestS(ns2.BaseS):

    __slots__ = [
        '_a_value',
        '_a_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 z=None,
                 a=None):
        super(ImportTestS, self).__init__(z)
        self._a_value = None
        self._a_present = False
        if a is not None:
            self.a = a

    @property
    def a(self):
        """
        :rtype: str
        """
        if self._a_present:
            return self._a_value
        else:
            raise AttributeError("missing required field 'a'")

    @a.setter
    def a(self, val):
        val = self._a_validator.validate(val)
        self._a_value = val
        self._a_present = True

    @a.deleter
    def a(self):
        self._a_value = None
        self._a_present = False

    def __repr__(self):
        return 'ImportTestS(z={!r}, a={!r})'.format(
            self._z_value,
            self._a_value,
        )

ImportTestS_validator = bv.Struct(ImportTestS)

class ImportTestU(ns2.BaseU):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.
    """

    @classmethod
    def a(cls, val):
        """
        Create an instance of this class set to the ``a`` tag with value
        ``val``.

        :param long val:
        :rtype: ImportTestU
        """
        return cls('a', val)

    def is_a(self):
        """
        Check if the union tag is ``a``.

        :rtype: bool
        """
        return self._tag == 'a'

    def get_a(self):
        """
        Only call this if :meth:`is_a` is true.

        :rtype: long
        """
        if not self.is_a():
            raise AttributeError("tag 'a' not set")
        return self._value

    def __repr__(self):
        return 'ImportTestU(%r, %r)' % (self._tag, self._value)

ImportTestU_validator = bv.Union(ImportTestU)

class OptionalS(object):

    __slots__ = [
        '_f1_value',
        '_f1_present',
        '_f2_value',
        '_f2_present',
    ]

    _has_required_fields = False

    def __init__(self,
                 f1=None,
                 f2=None):
        self._f1_value = None
        self._f1_present = False
        self._f2_value = None
        self._f2_present = False
        if f1 is not None:
            self.f1 = f1
        if f2 is not None:
            self.f2 = f2

    @property
    def f1(self):
        """
        :rtype: str
        """
        if self._f1_present:
            return self._f1_value
        else:
            return 'hello'

    @f1.setter
    def f1(self, val):
        val = self._f1_validator.validate(val)
        self._f1_value = val
        self._f1_present = True

    @f1.deleter
    def f1(self):
        self._f1_value = None
        self._f1_present = False

    @property
    def f2(self):
        """
        :rtype: long
        """
        if self._f2_present:
            return self._f2_value
        else:
            return 3

    @f2.setter
    def f2(self, val):
        val = self._f2_validator.validate(val)
        self._f2_value = val
        self._f2_present = True

    @f2.deleter
    def f2(self):
        self._f2_value = None
        self._f2_present = False

    def __repr__(self):
        return 'OptionalS(f1={!r}, f2={!r})'.format(
            self._f1_value,
            self._f2_value,
        )

OptionalS_validator = bv.Struct(OptionalS)

class S(object):

    __slots__ = [
        '_f_value',
        '_f_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 f=None):
        self._f_value = None
        self._f_present = False
        if f is not None:
            self.f = f

    @property
    def f(self):
        """
        :rtype: str
        """
        if self._f_present:
            return self._f_value
        else:
            raise AttributeError("missing required field 'f'")

    @f.setter
    def f(self, val):
        val = self._f_validator.validate(val)
        self._f_value = val
        self._f_present = True

    @f.deleter
    def f(self):
        self._f_value = None
        self._f_present = False

    def __repr__(self):
        return 'S(f={!r})'.format(
            self._f_value,
        )

S_validator = bv.Struct(S)

class S2(object):

    __slots__ = [
        '_f1_value',
        '_f1_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 f1=None):
        self._f1_value = None
        self._f1_present = False
        if f1 is not None:
            self.f1 = f1

    @property
    def f1(self):
        """
        :rtype: OptionalS
        """
        if self._f1_present:
            return self._f1_value
        else:
            raise AttributeError("missing required field 'f1'")

    @f1.setter
    def f1(self, val):
        self._f1_validator.validate_type_only(val)
        self._f1_value = val
        self._f1_present = True

    @f1.deleter
    def f1(self):
        self._f1_value = None
        self._f1_present = False

    def __repr__(self):
        return 'S2(f1={!r})'.format(
            self._f1_value,
        )

S2_validator = bv.Struct(S2)

class S3(object):

    __slots__ = [
        '_u_value',
        '_u_present',
    ]

    _has_required_fields = False

    def __init__(self,
                 u=None):
        self._u_value = None
        self._u_present = False
        if u is not None:
            self.u = u

    @property
    def u(self):
        """
        :rtype: ns2.BaseU_validator
        """
        if self._u_present:
            return self._u_value
        else:
            return ns2.BaseU.z

    @u.setter
    def u(self, val):
        self._u_validator.validate_type_only(val)
        self._u_value = val
        self._u_present = True

    @u.deleter
    def u(self):
        self._u_value = None
        self._u_present = False

    def __repr__(self):
        return 'S3(u={!r})'.format(
            self._u_value,
        )

S3_validator = bv.Struct(S3)

class U(bb.Union):
    """
    Sample union doc.

    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar t0: Sample field doc.
    """

    _catch_all = None
    # Attribute is overwritten below the class definition
    t0 = None

    @classmethod
    def t1(cls, val):
        """
        Create an instance of this class set to the ``t1`` tag with value
        ``val``.

        :param str val:
        :rtype: U
        """
        return cls('t1', val)

    def is_t0(self):
        """
        Check if the union tag is ``t0``.

        :rtype: bool
        """
        return self._tag == 't0'

    def is_t1(self):
        """
        Check if the union tag is ``t1``.

        :rtype: bool
        """
        return self._tag == 't1'

    def get_t1(self):
        """
        Only call this if :meth:`is_t1` is true.

        :rtype: str
        """
        if not self.is_t1():
            raise AttributeError("tag 't1' not set")
        return self._value

    def __repr__(self):
        return 'U(%r, %r)' % (self._tag, self._value)

U_validator = bv.Union(U)

class U2(bb.Union):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.
    """

    _catch_all = None
    # Attribute is overwritten below the class definition
    a = None

    @classmethod
    def b(cls, val):
        """
        Create an instance of this class set to the ``b`` tag with value
        ``val``.

        :param OptionalS val:
        :rtype: U2
        """
        return cls('b', val)

    def is_a(self):
        """
        Check if the union tag is ``a``.

        :rtype: bool
        """
        return self._tag == 'a'

    def is_b(self):
        """
        Check if the union tag is ``b``.

        :rtype: bool
        """
        return self._tag == 'b'

    def get_b(self):
        """
        Only call this if :meth:`is_b` is true.

        :rtype: OptionalS
        """
        if not self.is_b():
            raise AttributeError("tag 'b' not set")
        return self._value

    def __repr__(self):
        return 'U2(%r, %r)' % (self._tag, self._value)

U2_validator = bv.Union(U2)

class V(bb.Union):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.
    """

    _catch_all = 'other'
    # Attribute is overwritten below the class definition
    t0 = None
    # Attribute is overwritten below the class definition
    other = None

    @classmethod
    def t1(cls, val):
        """
        Create an instance of this class set to the ``t1`` tag with value
        ``val``.

        :param str val:
        :rtype: V
        """
        return cls('t1', val)

    @classmethod
    def t2(cls, val):
        """
        Create an instance of this class set to the ``t2`` tag with value
        ``val``.

        :param str val:
        :rtype: V
        """
        return cls('t2', val)

    @classmethod
    def t3(cls, val):
        """
        Create an instance of this class set to the ``t3`` tag with value
        ``val``.

        :param S val:
        :rtype: V
        """
        return cls('t3', val)

    @classmethod
    def t4(cls, val):
        """
        Create an instance of this class set to the ``t4`` tag with value
        ``val``.

        :param S val:
        :rtype: V
        """
        return cls('t4', val)

    @classmethod
    def t5(cls, val):
        """
        Create an instance of this class set to the ``t5`` tag with value
        ``val``.

        :param U val:
        :rtype: V
        """
        return cls('t5', val)

    @classmethod
    def t6(cls, val):
        """
        Create an instance of this class set to the ``t6`` tag with value
        ``val``.

        :param U val:
        :rtype: V
        """
        return cls('t6', val)

    @classmethod
    def t7(cls, val):
        """
        Create an instance of this class set to the ``t7`` tag with value
        ``val``.

        :param Resource val:
        :rtype: V
        """
        return cls('t7', val)

    @classmethod
    def t8(cls, val):
        """
        Create an instance of this class set to the ``t8`` tag with value
        ``val``.

        :param Resource val:
        :rtype: V
        """
        return cls('t8', val)

    @classmethod
    def t9(cls, val):
        """
        Create an instance of this class set to the ``t9`` tag with value
        ``val``.

        :param list of [str] val:
        :rtype: V
        """
        return cls('t9', val)

    @classmethod
    def t10(cls, val):
        """
        Create an instance of this class set to the ``t10`` tag with value
        ``val``.

        :param list of [U] val:
        :rtype: V
        """
        return cls('t10', val)

    def is_t0(self):
        """
        Check if the union tag is ``t0``.

        :rtype: bool
        """
        return self._tag == 't0'

    def is_t1(self):
        """
        Check if the union tag is ``t1``.

        :rtype: bool
        """
        return self._tag == 't1'

    def is_t2(self):
        """
        Check if the union tag is ``t2``.

        :rtype: bool
        """
        return self._tag == 't2'

    def is_t3(self):
        """
        Check if the union tag is ``t3``.

        :rtype: bool
        """
        return self._tag == 't3'

    def is_t4(self):
        """
        Check if the union tag is ``t4``.

        :rtype: bool
        """
        return self._tag == 't4'

    def is_t5(self):
        """
        Check if the union tag is ``t5``.

        :rtype: bool
        """
        return self._tag == 't5'

    def is_t6(self):
        """
        Check if the union tag is ``t6``.

        :rtype: bool
        """
        return self._tag == 't6'

    def is_t7(self):
        """
        Check if the union tag is ``t7``.

        :rtype: bool
        """
        return self._tag == 't7'

    def is_t8(self):
        """
        Check if the union tag is ``t8``.

        :rtype: bool
        """
        return self._tag == 't8'

    def is_t9(self):
        """
        Check if the union tag is ``t9``.

        :rtype: bool
        """
        return self._tag == 't9'

    def is_t10(self):
        """
        Check if the union tag is ``t10``.

        :rtype: bool
        """
        return self._tag == 't10'

    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        return self._tag == 'other'

    def get_t1(self):
        """
        Only call this if :meth:`is_t1` is true.

        :rtype: str
        """
        if not self.is_t1():
            raise AttributeError("tag 't1' not set")
        return self._value

    def get_t2(self):
        """
        Only call this if :meth:`is_t2` is true.

        :rtype: str
        """
        if not self.is_t2():
            raise AttributeError("tag 't2' not set")
        return self._value

    def get_t3(self):
        """
        Only call this if :meth:`is_t3` is true.

        :rtype: S
        """
        if not self.is_t3():
            raise AttributeError("tag 't3' not set")
        return self._value

    def get_t4(self):
        """
        Only call this if :meth:`is_t4` is true.

        :rtype: S
        """
        if not self.is_t4():
            raise AttributeError("tag 't4' not set")
        return self._value

    def get_t5(self):
        """
        Only call this if :meth:`is_t5` is true.

        :rtype: U
        """
        if not self.is_t5():
            raise AttributeError("tag 't5' not set")
        return self._value

    def get_t6(self):
        """
        Only call this if :meth:`is_t6` is true.

        :rtype: U
        """
        if not self.is_t6():
            raise AttributeError("tag 't6' not set")
        return self._value

    def get_t7(self):
        """
        Only call this if :meth:`is_t7` is true.

        :rtype: Resource
        """
        if not self.is_t7():
            raise AttributeError("tag 't7' not set")
        return self._value

    def get_t8(self):
        """
        Only call this if :meth:`is_t8` is true.

        :rtype: Resource
        """
        if not self.is_t8():
            raise AttributeError("tag 't8' not set")
        return self._value

    def get_t9(self):
        """
        Only call this if :meth:`is_t9` is true.

        :rtype: list of [str]
        """
        if not self.is_t9():
            raise AttributeError("tag 't9' not set")
        return self._value

    def get_t10(self):
        """
        Only call this if :meth:`is_t10` is true.

        :rtype: list of [U]
        """
        if not self.is_t10():
            raise AttributeError("tag 't10' not set")
        return self._value

    def __repr__(self):
        return 'V(%r, %r)' % (self._tag, self._value)

V_validator = bv.Union(V)

AliasedS2_validator = S2_validator
AliasedS2 = S2
AliasedString_validator = bv.String(max_length=10)
A._a_validator = bv.String()
A._b_validator = bv.Int64()
A._all_field_names_ = set([
    'a',
    'b',
])
A._all_fields_ = [
    ('a', A._a_validator),
    ('b', A._b_validator),
]

B._c_validator = bv.Bytes()
B._all_field_names_ = A._all_field_names_.union(set(['c']))
B._all_fields_ = A._all_fields_ + [('c', B._c_validator)]

C._d_validator = bv.Float64()
C._all_field_names_ = B._all_field_names_.union(set(['d']))
C._all_fields_ = B._all_fields_ + [('d', C._d_validator)]

ContainsAlias._s_validator = AliasedString_validator
ContainsAlias._all_field_names_ = set(['s'])
ContainsAlias._all_fields_ = [('s', ContainsAlias._s_validator)]

D._a_validator = bv.String()
D._b_validator = bv.UInt64()
D._c_validator = bv.Nullable(bv.String())
D._d_validator = bv.List(bv.Nullable(bv.Int64()))
D._all_field_names_ = set([
    'a',
    'b',
    'c',
    'd',
])
D._all_fields_ = [
    ('a', D._a_validator),
    ('b', D._b_validator),
    ('c', D._c_validator),
    ('d', D._d_validator),
]

DocTest._b_validator = bv.Boolean()
DocTest._t_validator = bv.String()
DocTest._all_field_names_ = set([
    'b',
    't',
])
DocTest._all_fields_ = [
    ('b', DocTest._b_validator),
    ('t', DocTest._t_validator),
]

E._a_validator = bv.String()
E._b_validator = bv.UInt64()
E._c_validator = bv.Nullable(bv.Int64())
E._all_field_names_ = set([
    'a',
    'b',
    'c',
])
E._all_fields_ = [
    ('a', E._a_validator),
    ('b', E._b_validator),
    ('c', E._c_validator),
]

Resource._name_validator = bv.String()
Resource._field_names_ = set(['name'])
Resource._all_field_names_ = Resource._field_names_
Resource._fields_ = [('name', Resource._name_validator)]
Resource._all_fields_ = Resource._fields_

Resource._tag_to_subtype_ = {
    ('file',): File_validator,
    ('folder',): Folder_validator,
}
Resource._pytype_to_tag_and_subtype_ = {
    File: (('file',), File_validator),
    Folder: (('folder',), Folder_validator),
}
Resource._is_catch_all_ = False

File._size_validator = bv.UInt64()
File._field_names_ = set(['size'])
File._all_field_names_ = Resource._all_field_names_.union(File._field_names_)
File._fields_ = [('size', File._size_validator)]
File._all_fields_ = Resource._all_fields_ + File._fields_

ResourceLax._name_validator = bv.String()
ResourceLax._field_names_ = set(['name'])
ResourceLax._all_field_names_ = ResourceLax._field_names_
ResourceLax._fields_ = [('name', ResourceLax._name_validator)]
ResourceLax._all_fields_ = ResourceLax._fields_

ResourceLax._tag_to_subtype_ = {
    ('file',): File2_validator,
    ('folder',): Folder2_validator,
}
ResourceLax._pytype_to_tag_and_subtype_ = {
    File2: (('file',), File2_validator),
    Folder2: (('folder',), Folder2_validator),
}
ResourceLax._is_catch_all_ = True

File2._size_validator = bv.UInt64()
File2._field_names_ = set(['size'])
File2._all_field_names_ = ResourceLax._all_field_names_.union(File2._field_names_)
File2._fields_ = [('size', File2._size_validator)]
File2._all_fields_ = ResourceLax._all_fields_ + File2._fields_

Folder._field_names_ = set([])
Folder._all_field_names_ = Resource._all_field_names_.union(Folder._field_names_)
Folder._fields_ = []
Folder._all_fields_ = Resource._all_fields_ + Folder._fields_

Folder2._field_names_ = set([])
Folder2._all_field_names_ = ResourceLax._all_field_names_.union(Folder2._field_names_)
Folder2._fields_ = []
Folder2._all_fields_ = ResourceLax._all_fields_ + Folder2._fields_

ImportTestS._a_validator = bv.String()
ImportTestS._all_field_names_ = ns2.BaseS._all_field_names_.union(set(['a']))
ImportTestS._all_fields_ = ns2.BaseS._all_fields_ + [('a', ImportTestS._a_validator)]

ImportTestU._a_validator = bv.UInt64()
ImportTestU._tagmap = {
    'a': ImportTestU._a_validator,
}
ImportTestU._tagmap.update(ns2.BaseU._tagmap)

OptionalS._f1_validator = bv.String()
OptionalS._f2_validator = bv.UInt64()
OptionalS._all_field_names_ = set([
    'f1',
    'f2',
])
OptionalS._all_fields_ = [
    ('f1', OptionalS._f1_validator),
    ('f2', OptionalS._f2_validator),
]

S._f_validator = bv.String()
S._all_field_names_ = set(['f'])
S._all_fields_ = [('f', S._f_validator)]

S2._f1_validator = OptionalS_validator
S2._all_field_names_ = set(['f1'])
S2._all_fields_ = [('f1', S2._f1_validator)]

S3._u_validator = ns2.BaseU_validator
S3._all_field_names_ = set(['u'])
S3._all_fields_ = [('u', S3._u_validator)]

U._t0_validator = bv.Void()
U._t1_validator = bv.String()
U._tagmap = {
    't0': U._t0_validator,
    't1': U._t1_validator,
}

U.t0 = U('t0')

U2._a_validator = bv.Void()
U2._b_validator = OptionalS_validator
U2._tagmap = {
    'a': U2._a_validator,
    'b': U2._b_validator,
}

U2.a = U2('a')

V._t0_validator = bv.Void()
V._t1_validator = bv.String()
V._t2_validator = bv.Nullable(bv.String())
V._t3_validator = S_validator
V._t4_validator = bv.Nullable(S_validator)
V._t5_validator = U_validator
V._t6_validator = bv.Nullable(U_validator)
V._t7_validator = Resource_validator
V._t8_validator = bv.Nullable(Resource_validator)
V._t9_validator = bv.List(bv.String())
V._t10_validator = bv.List(U_validator)
V._other_validator = bv.Void()
V._tagmap = {
    't0': V._t0_validator,
    't1': V._t1_validator,
    't2': V._t2_validator,
    't3': V._t3_validator,
    't4': V._t4_validator,
    't5': V._t5_validator,
    't6': V._t6_validator,
    't7': V._t7_validator,
    't8': V._t8_validator,
    't9': V._t9_validator,
    't10': V._t10_validator,
    'other': V._other_validator,
}

V.t0 = V('t0')
V.other = V('other')

ROUTES = {
}

