# -*- coding: utf-8 -*-
# Auto-generated by Stone, do not modify.
try:
    from . import stone_validators as bv
    from . import stone_base as bb
except (SystemError, ValueError):
    # Catch errors raised when importing a relative module when not in a package.
    # This makes testing this file directly (outside of a package) easier.
    import stone_validators as bv
    import stone_base as bb

class BaseS(object):
    """
    This is a test ♐
    """

    __slots__ = [
        '_z_value',
        '_z_present',
    ]

    _has_required_fields = True

    def __init__(self,
                 z=None):
        self._z_value = None
        self._z_present = False
        if z is not None:
            self.z = z

    @property
    def z(self):
        """
        :rtype: long
        """
        if self._z_present:
            return self._z_value
        else:
            raise AttributeError("missing required field 'z'")

    @z.setter
    def z(self, val):
        val = self._z_validator.validate(val)
        self._z_value = val
        self._z_present = True

    @z.deleter
    def z(self):
        self._z_value = None
        self._z_present = False

    def __repr__(self):
        return 'BaseS(z={!r})'.format(
            self._z_value,
        )

BaseS_validator = bv.Struct(BaseS)

class BaseU(bb.Union):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.
    """

    _catch_all = None
    # Attribute is overwritten below the class definition
    z = None

    @classmethod
    def x(cls, val):
        """
        Create an instance of this class set to the ``x`` tag with value
        ``val``.

        :param str val:
        :rtype: BaseU
        """
        return cls('x', val)

    def is_z(self):
        """
        Check if the union tag is ``z``.

        :rtype: bool
        """
        return self._tag == 'z'

    def is_x(self):
        """
        Check if the union tag is ``x``.

        :rtype: bool
        """
        return self._tag == 'x'

    def get_x(self):
        """
        Only call this if :meth:`is_x` is true.

        :rtype: str
        """
        if not self.is_x():
            raise AttributeError("tag 'x' not set")
        return self._value

    def __repr__(self):
        return 'BaseU(%r, %r)' % (self._tag, self._value)

BaseU_validator = bv.Union(BaseU)

AliasedBaseU_validator = BaseU_validator
AliasedBaseU = BaseU
BaseS._z_validator = bv.Int64()
BaseS._all_field_names_ = set(['z'])
BaseS._all_fields_ = [('z', BaseS._z_validator)]

BaseU._z_validator = bv.Void()
BaseU._x_validator = bv.String()
BaseU._tagmap = {
    'z': BaseU._z_validator,
    'x': BaseU._x_validator,
}

BaseU.z = BaseU('z')

ROUTES = {
}

